"""Provider stand-ins shared by the provider and bridge seam tests.

A provider that implements the whole fused interface with no bodies: the
neutral defaults (chooser metadata, capabilities, session verbs) are what
the seam tests read, so every method stays a no-op and each test subclasses
or wraps it for the behavior it pins.
"""

from __future__ import annotations

from waves.providers.base import Provider


class BareProvider(Provider):
    """A provider implementing the whole fused interface, with no bodies."""

    id = "x"
    name = "X"
    capabilities = frozenset()

    def login_begin(self): ...
    def login_complete(self, payload): ...
    def logout(self): ...

    @property
    def is_logged_in(self): ...

    def apply_quality(self, tier, audio_type): ...
    def search(self, needle): ...
    def open_url(self, url): ...
    def get_object(self, kind, raw_id): ...
    def collection_items(self, obj, include_videos=True): ...
    def user_collections(self): ...
    def favorites_page(self, kind, offset, limit, order=None): ...
    def favorite_ids(self, kind): ...
    def advertised_tier(self, obj): ...
    def advertised_deliveries(self, obj): ...
    def advertised_ceiling(self, obj): ...
    def resolve_stream(self, track, tier, audio_type): ...
    def fetch_lyrics(self, track): ...
    def cover_url(self, obj, dimension): ...
    def track_facts(self, track): ...
    def classify_refusal(self, exc): ...
    def login_resume(self): ...
    def account_id(self): ...
    def credential_facts(self): ...
    def reset_session(self): ...
    def folder_tree(self, root_folders=None): ...
    def search_tracks(self, needle, limit=10): ...
    def browse_page(self, title, api_path): ...
    def browse_home(self): ...
    def browse_window(self, title, data_path, mod_type, offset, limit=50): ...
