"""Install or verify repository-local hk hooks without changing shared hooks."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

EVENTS = ("pre-commit", "pre-push")


def git(*args: str) -> str:
    result = subprocess.run(["git", *args], capture_output=True, text=True, check=False)
    return result.stdout.strip() if result.returncode == 0 else ""


def hooks_dir() -> Path:
    return Path(git("rev-parse", "--path-format=absolute", "--git-path", "hooks"))


def is_hk_hook(path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    content = path.read_text(encoding="utf-8")
    return 'test "${HK:-1}" = "0"' in content and "hk run" in content


def verify() -> int:
    if git("config", "--get", "core.hooksPath"):
        print("FAIL: core.hooksPath is configured; repository hooks require coordination", file=sys.stderr)
        return 1
    for event in EVENTS:
        command = git("config", "--local", "--get", f"hook.hk-{event}.command")
        enabled = git("config", "--get", f"hook.hk-{event}.enabled")
        events = git("config", "--get-all", f"hook.hk-{event}.event").splitlines()
        hook = hooks_dir() / event
        expected = f'test "${{HK:-1}}" = "0" || mise x -- hk run {event} --from-hook'
        configured = command == expected and event in events and enabled != "false"
        shim = is_hk_hook(hook) and os.access(hook, os.X_OK) and "mise x -- hk" in hook.read_text()
        if not (configured or shim):
            print(f"FAIL: hk {event} hook missing or stale; run mise run install", file=sys.stderr)
            return 1
    print("ok: repository-local hk hooks installed")
    return 0


def install() -> int:
    if git("config", "--get", "core.hooksPath"):
        print("Refusing to change configured core.hooksPath; coordinate its owner first", file=sys.stderr)
        return 1
    if not git("rev-parse", "--git-dir"):
        print("Not a Git checkout", file=sys.stderr)
        return 1
    validated = subprocess.run(["hk", "validate"], check=False)
    if validated.returncode:
        return validated.returncode
    backups = []
    for event in EVENTS:
        path = hooks_dir() / event
        if not path.exists() and not path.is_symlink():
            continue
        if is_hk_hook(path):
            continue
        if path.is_symlink() or not path.is_file():
            print(f"Refusing to replace foreign hook {path}", file=sys.stderr)
            return 1
        content = path.read_text(encoding="utf-8")
        if "# File generated by pre-commit: https://pre-commit.com" not in content:
            print(f"Refusing to replace foreign hook {path}", file=sys.stderr)
            return 1
        backup = path.with_name(path.name + ".before-hk")
        if backup.exists() or backup.is_symlink():
            print(f"Refusing to overwrite hook backup {backup}", file=sys.stderr)
            return 1
        backups.append((path, backup))
    for path, backup in backups:
        path.rename(backup)
        print(f"Saved generated hook at {backup}")
    result = subprocess.run(["hk", "install", "--mise", "--force-local"], check=False)
    if result.returncode:
        # hk validates every target before writing. Preserve recoverable originals on failure.
        for path, backup in backups:
            if not path.exists():
                backup.rename(path)
        return result.returncode
    return verify()


if __name__ == "__main__":
    sys.exit(verify() if sys.argv[1:] == ["--check"] else install())
