"""Install or verify repository-local hk hooks without changing shared hooks."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

EVENTS = ("pre-commit", "pre-push")


def git(*args: str) -> str:
    result = subprocess.run(["git", *args], capture_output=True, text=True, check=False)
    return result.stdout.strip() if result.returncode == 0 else ""


def hooks_dir() -> Path:
    # --git-path hooks resolves symlinks and hides whether this directory is
    # shared. Inspect the lexical hooks path within the common Git directory.
    return Path(git("rev-parse", "--path-format=absolute", "--git-common-dir")) / "hooks"


def is_hk_hook(path: Path) -> bool:
    if path.is_symlink() or not path.is_file():
        return False
    content = path.read_text(encoding="utf-8")
    return 'test "${HK:-1}" = "0"' in content and "hk run" in content


def enabled(key: str) -> bool:
    result = subprocess.run(["git", "config", "--type=bool", "--get", key], capture_output=True, text=True, check=False)
    # Git's default is enabled when unset; malformed values must fail verification.
    return result.returncode == 1 or (result.returncode == 0 and result.stdout.strip() == "true")


def shared_hooks_directory() -> bool:
    return hooks_dir().is_symlink()


def hooks_path_configured() -> bool:
    result = subprocess.run(["git", "config", "--get", "core.hooksPath"], capture_output=True, check=False)
    return result.returncode == 0


def verify() -> int:
    if hooks_path_configured():
        print("FAIL: core.hooksPath is configured; repository hooks require coordination", file=sys.stderr)
        return 1
    if shared_hooks_directory():
        print("FAIL: hooks directory is symlinked; coordinate its owner first", file=sys.stderr)
        return 1
    for event in EVENTS:
        command = git("config", "--local", "--get", f"hook.hk-{event}.command")
        events = git("config", "--get-all", f"hook.hk-{event}.event").splitlines()
        hook = hooks_dir() / event
        expected = f'test "${{HK:-1}}" = "0" || mise x -- hk run {event} --from-hook'
        configured = command == expected and event in events and enabled(f"hook.hk-{event}.enabled")
        shim = (
            is_hk_hook(hook)
            and os.access(hook, os.X_OK)
            and f"mise x -- hk run {event} --from-hook" in hook.read_text()
        )
        # An active script also runs when native hooks are configured.
        stale_script = (hook.exists() or hook.is_symlink()) and not shim
        if stale_script or not (configured or shim):
            print(f"FAIL: hk {event} hook missing or stale; run mise run install", file=sys.stderr)
            return 1
    print("ok: repository-local hk hooks installed")
    return 0


def plan_hook_backups() -> list[tuple[Path, Path]] | None:
    # Validate all targets before the install transaction moves any generated hook.
    backups = []
    for event in EVENTS:
        path = hooks_dir() / event
        if not path.exists() and not path.is_symlink():
            continue
        if is_hk_hook(path):
            continue
        if path.is_symlink() or not path.is_file():
            print(f"Refusing to replace foreign hook {path}", file=sys.stderr)
            return None
        content = path.read_text(encoding="utf-8")
        if "# File generated by pre-commit: https://pre-commit.com" not in content:
            print(f"Refusing to replace foreign hook {path}", file=sys.stderr)
            return None
        backup = path.with_name(path.name + ".before-hk")
        if backup.exists() or backup.is_symlink():
            print(f"Refusing to overwrite hook backup {backup}", file=sys.stderr)
            return None
        backups.append((path, backup))
    return backups


def install() -> int:
    if hooks_path_configured():
        print("Refusing to change configured core.hooksPath; coordinate its owner first", file=sys.stderr)
        return 1
    if not git("rev-parse", "--git-dir"):
        print("Not a Git checkout", file=sys.stderr)
        return 1
    if shared_hooks_directory():
        print("Refusing to change a symlinked hooks directory; coordinate its owner first", file=sys.stderr)
        return 1
    validated = subprocess.run(["hk", "validate"], check=False)
    if validated.returncode:
        return validated.returncode
    backups = plan_hook_backups()
    if backups is None:
        return 1
    for path, backup in backups:
        path.rename(backup)
        print(f"Saved generated hook at {backup}")
    result = subprocess.run(["hk", "install", "--mise", "--force-local"], check=False)
    if result.returncode:
        # hk validates every target before writing. Preserve recoverable originals on failure.
        for path, backup in backups:
            if not path.exists():
                backup.rename(path)
        return result.returncode
    return verify()


if __name__ == "__main__":
    sys.exit(verify() if sys.argv[1:] == ["--check"] else install())
